"""add rating columns

Revision ID: 78f12fd2571a
Revises: ab4ad0c6051a
Create Date: 2026-03-05 09:49:47.369768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f12fd2571a'
down_revision: Union[str, None] = 'ab4ad0c6051a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
