"""Add email verification OTP fields to users

Revision ID: abcd1234efgh
Revises: 2864eacaefce
Create Date: 2026-04-16 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abcd1234efgh'
down_revision: Union[str, None] = '78f12fd2571a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verification_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verification_otp_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_otp')
    op.drop_column('users', 'email_verification_otp_expires')
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
